[project]
name = "python-advanced-course"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "annotated-types==0.7.0",
    "asttokens==3.0.1",
    "certifi==2026.2.25",
    "charset-normalizer==3.4.7",
    "colorama==0.4.6",
    "comm==0.2.3",
    "debugpy==1.8.20",
    "decorator==5.2.1",
    "dnspython==2.8.0",
    "email-validator==2.3.0",
    "executing==2.2.1",
    "idna==3.11",
    "iniconfig==2.3.0",
    "ipykernel==7.2.0",
    "ipython==9.10.1",
    "ipython-pygments-lexers==1.1.1",
    "jedi==0.19.2",
    "jupyter-client==8.8.0",
    "jupyter-core==5.9.1",
    "matplotlib-inline==0.2.1",
    "nest-asyncio==1.6.0",
    "numpy==2.4.4",
    "packaging==26.0",
    "pandas==3.0.2",
    "parso==0.8.6",
    "platformdirs==4.9.6",
    "pluggy==1.6.0",
    "prompt-toolkit==3.0.52",
    "psutil==7.2.2",
    "pure-eval==0.2.3",
    "pyarrow==23.0.1",
    "pydantic==2.13.0",
    "pydantic-core==2.46.0",
    "pygments==2.20.0",
    "pytest==9.0.3",
    "pytest-mock==3.15.1",
    "python-dateutil==2.9.0.post0",
    "pyzmq==27.1.0",
    "requests==2.33.1",
    "six==1.17.0",
    "stack-data==0.6.3",
    "tornado==6.5.5",
    "traitlets==5.14.3",
    "typing-extensions==4.15.0",
    "typing-inspection==0.4.2",
    "tzdata==2026.1",
    "urllib3==2.6.3",
    "wcwidth==0.6.0",
]

[dependency-groups]
dev = [
    "complexipy>=7.0.1",
]
